### ISSUE TITLE
为啥跑不起来啊，报错了。。

### ISSUE THREAD

**Issue by ganjmeng** [gingerJY/React-Native-Demo#1]
急需学习
![image](https://user-images.githubusercontent.com/12026835/41031017-37b23328-69b2-11e8-8bba-6bcb314b7c20.png)

**Comment by gingerJY** [comment]
网上找的解决办法，你可以试一下。
1: 启动项目的服务:react-native start或者npm start;然后早 Com+R;
2:上面的方法没有解决,而且长时间不能启动还报以上错误:
在 xcode ->build phases -> bundle react-native code and image->添加
export DISABLE_XIP=NOTHANKS或者:export DISABLE_XIP=true
原因详细介绍见 https://github.com/facebook/react-native/issues/12786

**Comment by gingerJY** [comment]
网上说是node版本问题，node需要降级到v8。
具体可以看一下这里：https://stackoverflow.com/questions/48357335/react-native-0-52-metro-bundler-has-encountered-an-internal-error
